# Site settings
title: Макар Бурнашев | Сайт-визитка
description: Сайт-визитка
lang: ru

# User settings
username: Макар Бурнашев
user_description: Студент совместной программы факультетов экономических наук и компьютерных наук НИУ ВШЭ в Москве. Работал с временными рядами, имею опыт ML проектов, командных хакатонов. Победитель олимпиад и кейс-чемпионатов. Стажер-аналитик рыночных рисков в НКЦ
user_title: Студент НИУ ВШЭ | Стажер НКЦ
resume_url: /assets/resume.pdf
email: maalburnashev@edu.hse.ru
telegram_username: maburnashev
linkedin_username: maburnashev
github_username: maburnashev
exclude: ['package.json', 'src', 'node_modules', 'vendor']

